#ifndef PRATOS_H
#define PRATOS_H

typedef enum {
    SOPA_DE_CEBOLA,
    SALADA_CAESAR,
    BRUSCHETTA,
    CARPACCIO_DE_CARNE,
    CAMARAO_AO_ALHO,
    LASANHA_A_BOLONHESA,
    FILE_MIGNON_COM_FRITAS,
    FRANGO_GRELHADO_COM_LEGUMES,
    BACALHAU_A_GOMES_DE_SA,
    RISOTO_DE_COGUMELOS,
    TIRAMISU,
    CHEESECAKE_DE_FRUTAS_VERMELHAS,
    MOUSSE_DE_CHOCOLATE,
    PUDIM_DE_LEITE,
    SORVETE_DE_BAUNILHA_COM_CALDA_DE_MORANGO,
    NUM_PRATOS 
} PratoEnum;

const char* obterNomePrato(PratoEnum prato);

#endif
